- hosts: all
  become: True
  gather_facts: False
  tasks:
    - name: check if mirror.in2p3.fr is reachable
      command: curl -m 1 http://mirror.in2p3.fr
      ignore_errors: yes
      changed_when: false

    - name: create /etc/rhsm/ca directory
      file:
        path: /etc/rhsm/ca
        state: directory
        mode: '0755'

    - name: create empty redhat-uep.pem
      file:
        path: /etc/rhsm/ca/redhat-uep.pem
        state: touch

    - name: disable fastestmirror plugin
      lineinfile:
        path: /etc/yum/pluginconf.d/fastestmirror.conf
        regexp: '^enable='
        line: enable=0

    - name: install repositories
      loop:
        - name: os
          url: http://mirror.in2p3.fr/linux/CentOS/7/os/x86_64/
        - name: extras
          url: http://mirror.in2p3.fr/linux/CentOS/7/extras/x86_64/
        - name: epel
          url: http://mirror.in2p3.fr/pub/epel/7/x86_64/
      yum_repository:
        name: "mirror_in2p3_{{ item.name }}"
        description: "in2p3 {{ item.name }} repository"
        baseurl: "{{ item.url }}"
        enabled: true
        gpgcheck: no
        sslverify: no

    - name: install required packages
      yum:
        name: "{{ packages }}"
        state: latest
      vars:
        packages:
          - PyYAML
          - net-tools
          - tmux
          - htop

    - name: upgrade all packages
      yum:
        name: '*'
        state: latest

    - name: set hostname
      hostname:
        name: "{{ inventory_hostname }}"

- import_playbook: ../openshift-ansible/playbooks/prerequisites.yml
- import_playbook: ../openshift-ansible/playbooks/openshift-checks/pre-install.yml
